// src/services/ai/providers/MockProvider.ts
// ─────────────────────────────────────────────────────────────
// Mock AI provider for development, testing, and demos.
//
// Features:
//   • Zero API calls — works offline, costs nothing
//   • Section-aware responses (different text per generation step)
//   • Simulated streaming with configurable delay
//   • Deterministic — same input always produces same output
//   • Instant testConnection() — always succeeds
//
// Activate by setting AI Provider to "Mock — Demo Mode" in
// Configuration → AI Behavior.
// ─────────────────────────────────────────────────────────────

import type {
  IAIProvider,
  AIGenerationRequest,
  AIGenerationResult,
  AIStreamCallback,
  AIConnectionTest,
} from '../IAIProvider';

// ── Canned responses per generation step ID ───────────────────
// Keyed by the section IDs from narrativeTemplateConfig.
// Add new entries here as new generation steps are added.

const MOCK_NARRATIVES: Record<string, string> = {
  admin_header:
    'Administrative and clinical information has been reviewed and documented ' +
    'per the submitted requisition. Patient demographics, accession details, ' +
    'and the requesting clinician are recorded as provided. The stated clinical ' +
    'indication has been noted and informs the pathological evaluation.',

  gross_description:
    'The specimen is received in formalin fixative, appropriately labeled in ' +
    'accordance with the submitted requisition. Gross examination reveals tissue ' +
    'that is adequate for histological evaluation. Representative sections have ' +
    'been submitted for processing per standard laboratory protocol. Block ' +
    'allocation is documented in the gross description worksheet.',

  synoptic_summary:
    'Synoptic data fields have been completed and are summarized as follows. ' +
    'Histologic type and tumor grade are recorded per the structured data panel. ' +
    'Tumor dimensions, margin status, and lymphovascular invasion status are ' +
    'documented in the synoptic fields. pTNM staging parameters have been ' +
    'assigned based on the submitted specimen and available clinical context.',

  ancillary_and_diagnosis:
    'Ancillary immunohistochemical studies have been performed as clinically ' +
    'indicated and are interpreted in the context of the morphological findings. ' +
    'Molecular studies, where obtained, are incorporated into the final diagnostic ' +
    'assessment. The final diagnosis reflects integration of all available ' +
    'histological, immunophenotypic, and ancillary data as documented above.',

  // Fallback for any unrecognised section IDs
  _default:
    'This generation step has been completed using mock data for demonstration ' +
    'purposes. In production, content is generated by the active AI provider ' +
    'from the structured case data and clinical context supplied by the ' +
    'Orchestrator Engine.',
};

// ── Word-by-word streaming delay ──────────────────────────────
// 25ms per word ≈ natural reading speed for demos.
// Set to 0 for unit tests to avoid test timeouts.

const DEFAULT_STREAM_DELAY_MS = 25;

const delay = (ms: number) => new Promise<void>(res => setTimeout(res, ms));

// Heuristic: match section IDs embedded in the prompt text

function resolveSectionId(prompt: string): string {
  const known = Object.keys(MOCK_NARRATIVES).filter(k => k !== '_default');
  const lp    = prompt.toLowerCase();
  return known.find(id => lp.includes(id.replace(/_/g, ' '))) ?? '_default';
}

// ── MockProvider ──────────────────────────────────────────────

export class MockProvider implements IAIProvider {
  readonly providerId   = 'mock';
  readonly modelId      = 'mock-v1';
  readonly displayName  = 'Mock — Demo Mode';

  private streamDelayMs: number;

  /**
   * @param streamDelayMs  Milliseconds between word emissions.
   *                       Default 25ms. Set to 0 for instant (unit tests).
   */
  constructor(streamDelayMs = DEFAULT_STREAM_DELAY_MS) {
    this.streamDelayMs = streamDelayMs;
  }

  private getMockText(request: AIGenerationRequest): string {
    const sectionId = resolveSectionId(request.prompt);
    return MOCK_NARRATIVES[sectionId] ?? MOCK_NARRATIVES._default;
  }

  // ── generate (non-streaming) ──────────────────────────────

  async generate(request: AIGenerationRequest): Promise<AIGenerationResult> {
    const startMs = Date.now();
    const text    = this.getMockText(request);

    // Small artificial pause so callers don't have to handle
    // synchronous-feeling async in edge cases
    await delay(this.streamDelayMs * 4);

    return {
      text,
      tokensGenerated: text.length,
      providerId:      this.providerId,
      modelId:         this.modelId,
      latencyMs:       Date.now() - startMs,
    };
  }

  // ── generateStream ────────────────────────────────────────

  async generateStream(
    request: AIGenerationRequest,
    onToken: AIStreamCallback,
  ): Promise<AIGenerationResult> {
    const startMs = Date.now();
    const text    = this.getMockText(request);
    const words   = text.split(' ');

    for (const word of words) {
      if (request.abortSignal?.aborted) break;
      onToken(word + ' ');
      if (this.streamDelayMs > 0) await delay(this.streamDelayMs);
    }

    return {
      text,
      tokensGenerated: text.length,
      providerId:      this.providerId,
      modelId:         this.modelId,
      latencyMs:       Date.now() - startMs,
    };
  }

  // ── testConnection ────────────────────────────────────────

  async testConnection(): Promise<AIConnectionTest> {
    return {
      ok:        true,
      message:   'Mock provider ready — no API connection required',
      latencyMs: 0,
    };
  }
}
