// src/types/case/SpecimenFlag.ts
// ─────────────────────────────────────────────────────────────
// Clinical-grade flag model for specimen-level annotations.
// Supports:
//   • LIS interoperability (lisCode)
//   • Severity scoring (1–5)
//   • Auditability (createdBy, createdAt, retiredAt)
//   • Category grouping
//   • Case vs specimen applicability
//   • UI color + description
// ─────────────────────────────────────────────────────────────

export interface SpecimenFlag {
  /** Unique identifier for this flag definition */
  id: string;

  /** Human-readable label, e.g. "Margin Involved", "Specimen Mislabeled" */
  label: string;

  /** Hex or semantic color (UI only) */
  color: string;

  /** Optional description for admins or UI tooltips */
  description?: string;

  /** LIS or external system code (e.g. "MARGIN", "MISLABEL", "QA") */
  lisCode?: string;

  /** Severity rating (1–5), where 5 is highest urgency */
  severity?: 1 | 2 | 3 | 4 | 5;

  /** Category grouping for filtering and UI organization */
  category?: "clinical" | "workflow" | "quality" | "safety" | "regulatory" | "billing" | "other";

  /** Whether this flag applies to specimen-level, case-level, or both */
  level?: "specimen" | "case" | "both";

  /** Audit metadata */
  createdAt?: string;   // ISO timestamp
  createdBy?: string;   // user ID
  retiredAt?: string | null;
  retiredBy?: string | null;

  /** Whether this flag is active in the system */
  active?: boolean;

  /** Whether this flag was auto-generated by the system */
  autoCreated?: boolean;
}